// ===== LUXURY RENTAL FLEET =====
const CARS = [
  {
    id: 1,
    year: 2024, make: "Ferrari", model: "Roma", trim: "Spider",
    type: "Coupe", color: "Rosso Corsa",
    price: 2800,
    mileage: 850,
    engine: "3.9L Twin-Turbo V8", transmission: "8-Speed DCT",
    mpg: "14/20", doors: 2,
    badge: "Featured",
    emoji: "🏎️",
    features: ["671 HP", "Retractable Soft Top", "Manettino Drive Modes", "Ferrari Dynamic Enhancer", "Carbon Ceramic Brakes", "JBL Premium Audio", "20-inch Forged Wheels", "Launch Control"],
    description: "The Ferrari Roma Spider is a modern masterpiece — a convertible grand tourer with 671 horsepower and breathtaking Italian design. Open the top, feel the wind, and experience la dolce vita at its finest."
  },
  {
    id: 2,
    year: 2024, make: "Lamborghini", model: "Huracán", trim: "EVO Spyder",
    type: "Coupe", color: "Giallo Orion",
    price: 3200,
    mileage: 620,
    engine: "5.2L Naturally Aspirated V10", transmission: "7-Speed LDF",
    mpg: "13/18", doors: 2,
    badge: "Popular",
    emoji: "🏎️",
    features: ["640 HP", "All-Wheel Drive", "ANIMA Drive Modes", "Retractable Soft Top", "Carbon Ceramic Brakes", "Lifting System", "Lamborghini Infotainment", "Race Exhaust"],
    description: "The Huracán EVO Spyder delivers the purest supercar experience. A screaming naturally-aspirated V10, AWD grip, and a retractable top — this is the open-air supercar dream made real."
  },
  {
    id: 3,
    year: 2024, make: "Rolls-Royce", model: "Ghost", trim: "Extended",
    type: "Sedan", color: "Andalusian White",
    price: 3500,
    mileage: 410,
    engine: "6.75L Twin-Turbo V12", transmission: "8-Speed Auto",
    mpg: "14/21", doors: 4,
    badge: "Ultra Luxury",
    emoji: "🚗",
    features: ["563 HP", "Starlight Headliner", "Bespoke Audio System", "Massage Seats", "Night Vision", "Head-Up Display", "Self-Closing Doors", "Rear Theatre Configuration"],
    description: "The Rolls-Royce Ghost Extended is the pinnacle of automotive luxury. A limousine wheelbase, a whisper-quiet V12, and a hand-crafted interior that rivals the finest five-star hotels in the world."
  },
  {
    id: 4,
    year: 2023, make: "Bentley", model: "Continental GT", trim: "Speed",
    type: "Coupe", color: "Verdant",
    price: 2200,
    mileage: 1800,
    engine: "6.0L W12 Twin-Turbo", transmission: "8-Speed DSG",
    mpg: "12/20", doors: 2,
    badge: "Grand Tourer",
    emoji: "🚗",
    features: ["659 HP", "48V Active Roll Control", "Rotating Centre Display", "Naim Premium Audio", "Diamond Quilted Interior", "All-Wheel Steering", "22-inch Forged Wheels", "Adaptive Cruise Control"],
    description: "The Continental GT Speed is the ultimate grand tourer — 659hp from a W12, a hand-stitched interior of the finest materials, and enough refinement to cross continents in absolute comfort."
  },
  {
    id: 5,
    year: 2024, make: "McLaren", model: "720S", trim: "Performance",
    type: "Coupe", color: "Papaya Spark",
    price: 2600,
    mileage: 1100,
    engine: "4.0L Twin-Turbo V8", transmission: "7-Speed SSG",
    mpg: "15/22", doors: 2,
    badge: "Track Ready",
    emoji: "🏎️",
    features: ["710 HP", "Monocage II Carbon Chassis", "Variable Drift Control", "Active Chassis Control", "Panoramic Dihedral Doors", "Bowers & Wilkins Audio", "Track Telemetry", "Carbon Fiber Pack"],
    description: "The McLaren 720S is a technical tour de force. 710hp from a twin-turbo V8, a carbon fiber monocoque, and active aerodynamics that blur the line between road car and race car."
  },
  {
    id: 6,
    year: 2024, make: "Porsche", model: "911", trim: "Turbo S Cabriolet",
    type: "Coupe", color: "GT Silver Metallic",
    price: 1800,
    mileage: 920,
    engine: "3.7L Twin-Turbo Flat-6", transmission: "8-Speed PDK",
    mpg: "17/24", doors: 2,
    badge: "Iconic",
    emoji: "🏎️",
    features: ["640 HP", "All-Wheel Drive", "Sport Chrono Package", "PASM Suspension", "Carbon Ceramic Brakes", "Bose Surround Sound", "Retractable Roof", "Night Vision Assist"],
    description: "The 911 Turbo S Cabriolet is the definitive sports car. 640hp, a lightning PDK gearbox, and 0-60 in under 2.7 seconds — with the roof down. This is what driving is supposed to feel like."
  },
  {
    id: 7,
    year: 2024, make: "Aston Martin", model: "DB12", trim: "Volante",
    type: "Coupe", color: "Fiamma",
    price: 2000,
    mileage: 740,
    engine: "4.0L Twin-Turbo V8", transmission: "8-Speed Automatic",
    mpg: "16/23", doors: 2,
    badge: "British Elegance",
    emoji: "🚗",
    features: ["671 HP", "Retractable Roof", "Adaptive Suspension", "Bang & Olufsen Audio", "360-Degree Camera", "Heated & Ventilated Seats", "Driver Display", "Carbon Fiber Interior Trim"],
    description: "James Bond's car of choice. The DB12 Volante combines breathtaking British styling with 671 horsepower and an open top. It is the world's first super tourer — sophistication and performance, inseparably bound."
  },
  {
    id: 8,
    year: 2024, make: "Mercedes-AMG", model: "G63", trim: "Edition 55",
    type: "SUV", color: "Obsidian Black",
    price: 1600,
    mileage: 2300,
    engine: "4.0L Biturbo V8", transmission: "9-Speed AMG Speedshift",
    mpg: "13/16", doors: 4,
    badge: "Statement",
    emoji: "🚙",
    features: ["577 HP", "AMG RIDE CONTROL", "Three Locking Differentials", "Burmester Audio", "MBUX Infotainment", "Designo Exclusive Interior", "Active Parking Assist", "Ambient Lighting"],
    description: "The G63 is the ultimate statement vehicle. Iconic boxy silhouette, a 577hp AMG V8, and enough presence to stop traffic in any city. The uncompromising SUV for uncompromising people."
  },
  {
    id: 9,
    year: 2023, make: "Maserati", model: "GranTurismo", trim: "Modena",
    type: "Coupe", color: "Blu Emozione",
    price: 1400,
    mileage: 3800,
    engine: "3.0L Twin-Turbo V6 Nettuno", transmission: "8-Speed Automatic",
    mpg: "15/21", doors: 2,
    badge: null,
    emoji: "🏎️",
    features: ["490 HP", "Nettuno F1-Derived Engine", "GT Sport Package", "Sonus Faber Audio", "Full-Grain Leather", "Carbon Interior Accents", "Skyhook Suspension", "20-inch Alloy Wheels"],
    description: "The reborn GranTurismo carries 70 years of Italian racing DNA. The Nettuno engine — derived from Maserati's F1 program — delivers a sound and sensation unlike anything else in its class."
  },
  {
    id: 10,
    year: 2024, make: "BMW", model: "M8", trim: "Gran Coupé Competition",
    type: "Sedan", color: "Dravit Grey",
    price: 1200,
    mileage: 4200,
    engine: "4.4L Twin-Turbo V8", transmission: "8-Speed M Steptronic",
    mpg: "16/23", doors: 4,
    badge: null,
    emoji: "🚗",
    features: ["617 HP", "M xDrive AWD", "Carbon Fiber Roof", "Merino Leather Interior", "Bowers & Wilkins Diamond Audio", "M Driver's Package", "Active M Differential", "Laser Headlights"],
    description: "The M8 Gran Coupé Competition is BMW's pinnacle: 617hp, all-wheel drive, and four doors wrapped in a body that looks like it was sculpted by hand. Power and luxury — perfectly fused."
  },
  {
    id: 11,
    year: 2024, make: "Range Rover", model: "Sport", trim: "SV Edition",
    type: "SUV", color: "Lantau Bronze",
    price: 1100,
    mileage: 5600,
    engine: "4.4L Twin-Turbo V8", transmission: "8-Speed Automatic",
    mpg: "16/21", doors: 4,
    badge: null,
    emoji: "🚙",
    features: ["530 HP", "Air Suspension", "Wade Sensing", "Meridian Signature Sound", "Pivi Pro Infotainment", "Massage Seats", "Pixel LED Headlights", "22-inch Satin Dark Wheels"],
    description: "Effortlessly capable and unmistakably elegant, the Range Rover Sport SV Edition combines a biturbo V8 with the refinement and presence that only a Range Rover can deliver. Perfect for any terrain."
  },
  {
    id: 12,
    year: 2024, make: "Lamborghini", model: "Urus", trim: "Performante",
    type: "SUV", color: "Nero Noctis",
    price: 2400,
    mileage: 890,
    engine: "4.0L Twin-Turbo V8", transmission: "8-Speed Automatic",
    mpg: "12/17", doors: 4,
    badge: "Rare Find",
    emoji: "🚙",
    features: ["657 HP", "Carbon Ceramic Brakes", "Corsa Drive Mode", "Carbon Fiber Roof", "All-Wheel Drive", "Rear-Axle Steering", "Alcantara Interior", "23-inch Forged Wheels"],
    description: "The Urus Performante is the super SUV redefined. With 657hp, a carbon ceramic brake system, and dedicated track modes, it delivers supercar performance in an all-terrain body. Nothing else compares."
  }
];
